name-template: "Release $NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - feature
  - title: "🐛 Bug Fixes"
    labels:
      - fix
  - title: "🛠 Maintenance"
    labels:
      - refactor
change-template: "- $TITLE (#$NUMBER by @$AUTHOR)"
template: |
  ## Changes
  $CHANGES
