name: Release Drafter

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if tag is on main branch
        id: check_branch
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BRANCH=$(git branch -r --contains $TAG_NAME | grep 'origin/main' || true)
          if [ -z "$BRANCH" ]; then
            echo "Tag is not on main branch"
            exit 1
          fi

      - name: Generate and Prepend Changelog
        run: |
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${CURRENT_TAG}^)
          
          echo "# ${CURRENT_TAG} ($(git log -1 --format=%ai ${CURRENT_TAG}))" > temp_changelog.txt
          echo "" >> temp_changelog.txt
          
          TAG_MESSAGE=$(git tag -l --format='%(contents)' ${CURRENT_TAG})
          if [ ! -z "$TAG_MESSAGE" ]; then
            echo "## Release Notes" >> temp_changelog.txt
            echo "$TAG_MESSAGE" >> temp_changelog.txt
            echo "" >> temp_changelog.txt
          fi
          
          echo "## Commits" >> temp_changelog.txt
          git log --pretty=format:"* %h - %s (%an)" ${PREVIOUS_TAG}..${CURRENT_TAG} >> temp_changelog.txt
          echo "" >> temp_changelog.txt
          echo "" >> temp_changelog.txt
          
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md >> temp_changelog.txt
          fi
          
          mv temp_changelog.txt CHANGELOG.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git diff --staged --quiet || git commit -m 'Update changelog'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}