name: Release Drafter

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine branch
        id: get_branch
        run: echo "::set-output name=branch::$(git symbolic-ref --short HEAD || echo 'main')"

      - name: Generate and Prepend Changelog
        run: |
          # Guardar los logs nuevos en un archivo temporal
          git log --pretty=format:"%h - %an, %ar : %s" $(git describe --tags --abbrev=0 @^)..@ > temp_changelog.txt
          
          # Si CHANGELOG.md existe, combinar los archivos
          if [ -f CHANGELOG.md ]; then
            # Agregar una línea en blanco entre los logs nuevos y antiguos
            echo "" >> temp_changelog.txt
            echo "" >> temp_changelog.txt
            cat CHANGELOG.md >> temp_changelog.txt
          fi
          
          # Mover el archivo temporal a CHANGELOG.md
          mv temp_changelog.txt CHANGELOG.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout ${{ steps.get_branch.outputs.branch }}
          git pull origin ${{ steps.get_branch.outputs.branch }}
          git add CHANGELOG.md
          git commit -m 'Update changelog'
          git push origin ${{ steps.get_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}